import assert from 'node:assert/strict';
import fs from 'node:fs';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fixture = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));
const browser = await chromium.launch({ headless: true, executablePath: process.env.BROWSER_EXECUTABLE || undefined });
const output = process.env.LEGAL_SCREENSHOTS || '/tmp/theses-legal-screenshots';
fs.mkdirSync(output, { recursive: true });
try {
  const staff = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
  await staff.addCookies(fixture.cookies);
  const page = await staff.newPage();
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(fixture.url + '/p/' + fixture.proposition);
  await page.getByRole('link', { name: 'Releases', exact: true }).click();
  await page.getByLabel('Title', { exact: true }).fill('Conversations on the street');
  await page.getByLabel('Brand / show name').fill('Example Radio');
  await page.getByLabel('Legal rights holder').fill('Example LLC');
  await page.getByLabel('Recording details').fill('A conversation about our changing city. Recorded at the public market.');
  await page.getByLabel('Governing state').selectOption('GA');
  await page.getByLabel('Release type').selectOption('interview');
  assert.match(await page.locator('#release-body').inputValue(), /be interviewed/);
  await page.getByText('Start from a draft template', { exact: true }).click();
  await page.getByRole('button', { name: 'Use selected release template' }).click();
  assert.match(await page.locator('#release-body').inputValue(), /be interviewed/);
  await page.getByRole('button', { name: /Create link & QR/ }).click();
  await page.waitForURL('**/releases/*');
  const managePath = new URL(page.url()).pathname;
  const releaseURL = await page.locator('#release-url').inputValue();
  const releasePath = new URL(releaseURL).pathname;
  for (const width of [320,390,768,1024,1440]) {
    await page.setViewportSize({ width, height: 1100 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'staff overflow at ' + width);
    await page.screenshot({ path: `${output}/staff-${width}.png`, fullPage: true });
  }
  const anon = await browser.newContext({ viewport: { width: 390, height: 844 } });
  const form = await anon.newPage();
  form.on('pageerror', e => errors.push(e.message));
  await form.goto(fixture.url + releasePath);
  assert.ok(await form.getByText('This release is governed by the laws of the State of Georgia', { exact: false }).isVisible());
  assert.ok(await form.getByText('I authorize Example LLC', { exact: false }).isVisible());
  assert.equal(await form.getByRole('link', { name: 'Back to workspace' }).count(), 0);
  for (const width of [320,390,768,1024,1440]) {
    await form.setViewportSize({ width, height: 1000 });
    assert.ok(await form.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'public overflow at ' + width);
    await form.screenshot({ path: `${output}/public-${width}.png`, fullPage: true });
  }
  await form.setViewportSize({ width: 390, height: 844 });
  await form.getByRole('button', { name: '+ Add person' }).click();
  assert.equal(await form.locator('.person').count(), 2);
  await form.locator('.person').nth(1).getByRole('button', { name: 'Remove person' }).click();
  await form.getByRole('button', { name: '+ Add person' }).click();
  const first = form.locator('.person').nth(0), second = form.locator('.person').nth(1);
  await first.getByLabel('Full name / typed signature').fill('Ada Lovelace');
  await first.getByLabel('Email optional').fill('ada@example.com');
  await first.getByLabel('Email me when this episode is available.').check();
  await first.getByLabel('I am at least 18').check();
  await form.getByRole('button', { name: '+ Add person' }).click();
  const third = form.locator('.person').nth(2);
  assert.equal(await third.getByLabel('Email optional').getAttribute('required'), null);
  await third.getByRole('button', { name: 'Remove person' }).click();
  await second.getByLabel('Full name / typed signature').fill('Grace Hopper');
  await form.getByRole('button', { name: 'Sign & submit' }).click();
  assert.equal(new URL(form.url()).pathname, releasePath, 'missing individual consent prevents submit');
  await second.getByLabel('I am at least 18').check();
  await form.getByRole('button', { name: 'Sign & submit' }).click();
  await form.waitForURL('**/receipt/*');
  assert.ok(await form.getByRole('status').isVisible());
  assert.ok(await form.getByText('Ada Lovelace', { exact: true }).isVisible());
  assert.ok(await form.getByText('Grace Hopper', { exact: true }).isVisible());
  await form.screenshot({ path: `${output}/receipt-390.png`, fullPage: true });
  const receiptPath = new URL(form.url()).pathname;
  const json = await anon.request.get(fixture.url + receiptPath + '?download=1');
  const signed = await json.json();
  assert.equal(signed.agreement.state, 'GA');
  assert.equal(signed.people.length, 2);
  await page.goto(fixture.url + managePath);
  await page.getByLabel('Governing state').selectOption('NY');
  await page.getByLabel('Release wording').fill('Updated agreement for {rights_holder}.');
  await page.getByRole('button', { name: /Save changes/ }).click();
  await page.waitForURL('**/releases/*');
  await form.reload();
  assert.ok(await form.getByText('This release is governed by the laws of the State of Georgia', { exact: false }).isVisible());
  await page.getByLabel('Published episode URL').fill('https://example.com/episodes/street-voices');
  await page.getByRole('button', { name: 'Preview email', exact: true }).click();
  assert.ok(await page.getByRole('heading', { name: '1 recipients ready' }).isVisible());
  assert.ok(await page.getByText('ada@example.com', { exact: false }).last().isVisible());
  const ready = page.locator('#email-preview');
  await ready.locator('summary').click();
  assert.match(await ready.locator('pre').innerText(), /Hello Ada Lovelace/);
  assert.match(await ready.locator('pre').innerText(), /https:\/\/example.com\/episodes\/street-voices/);
  await page.screenshot({ path: `${output}/email-preview.png`, fullPage: true });
  await page.getByLabel('Title', { exact: true }).fill('Conversations, revised');
  await page.getByRole('button', { name: /Save changes/ }).click();
  await page.waitForURL(fixture.url + managePath);
  assert.equal(await page.getByLabel('Title', { exact: true }).inputValue(), 'Conversations, revised');
  await page.goto(fixture.url + releasePath + '/qr');
  await page.locator('.qr-page img').waitFor({ state: 'visible' });
  await page.screenshot({ path: `${output}/qr-1440.png`, fullPage: true });
  const svg = await (await staff.request.get(fixture.url + releasePath + '/qr.svg')).text();
  assert.match(svg, /Example Radio/);
  assert.match(svg, /shape-rendering="crispEdges"/);
  await page.goto(fixture.url + managePath);
  await page.getByLabel('Close this link to new signatures').check();
  await page.getByRole('button', { name: /Save changes/ }).click();
  await page.waitForURL('**/releases/*');
  await form.goto(fixture.url + releasePath);
  assert.ok(await form.getByRole('heading', { name: 'This release is closed.' }).isVisible());
  assert.equal(await form.locator('#sign-form').count(), 0);
  const denied = await anon.request.get(fixture.url + managePath + '/export', { maxRedirects: 0 });
  assert.equal(denied.status(), 303);
  assert.deepEqual(errors, []);
  console.log('Legal create, multi-person consent, receipt, immutable state, email preview, QR, closed link, permissions and five viewport checks passed.');
} finally { await browser.close(); }
