import assert from 'node:assert/strict';
import { defaultFilters, cleanFilters, matchesCard, calendarDay } from './static/app/filters.js';
const card = {title:'Review @[p:42]',description_md:'Find supporting evidence',assignees:[7],due_date:'2026-09-21'};
const matches=(filter, row=card)=>matchesCard(row,{...defaultFilters(),...filter},7,'2026-09-21');
assert.equal(matches({status:'mine'}),true);
assert.equal(matches({assignee:'8'}),false);
assert.equal(matches({proposition:'42',query:'EVIDENCE'}),true);
assert.equal(matches({proposition:'43'}),false);
assert.equal(matches({due:'today'}),true);
assert.equal(matches({due:'overdue'}),false);
assert.equal(matches({due:'upcoming'}),false);
assert.equal(matches({due:'overdue'},{...card,due_date:'2026-09-20'}),true);
assert.equal(matches({due:'today'},{...card,done_at:1}),false);
assert.equal(matches({due:'none'},{...card,due_date:null}),true);
assert.equal(matches({status:'open'},{...card,done_at:1}),false);
assert.equal(cleanFilters({assignee:'bad',proposition:-1,view:'other',query:'x'.repeat(300)}).query.length,200);
assert.deepEqual(cleanFilters(null),defaultFilters());
assert.equal(calendarDay('America/New_York',new Date('2026-09-21T02:00:00Z')),'2026-09-20');
assert.match(calendarDay('invalid-zone'),/^\d{4}-\d{2}-\d{2}$/);
